#单接口yml模板:
- name: login
  method: POST
  url: /dolphinscheduler/login
  headers: ~
  params: ~
  data:
    userName: 'admin'
    userPassword: 'dolphinscheduler123'
  json: ~
  validate:
    statusCode: 200
    errorCode: 0
    msg: 成功
  extract:
    body:
    securityConfigType: data.securityConfigType
    sessionId: data.sessionId
    headers: ~
  depend:
    headers: ~
    params: ~
    data: ~
    json: ~
#单接口yml模板:
- name: projects
  method: POST
  url: /dolphinscheduler/projects
  headers:
    essionid: '6246fd9c-b9e8-40f0-af64-90e5482fedbd'
    securityConfigType :
  params: ~
  data:
    projectName: 21
    userName: 'admin'
  json: ~
  validate:
    statusCode: 200
    errorCode: 200
    msg: 成功
  extract:
    body:
    headers:
  depend:
    headers: ~
    params: ~
    data: ~
    json: ~